import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import Cube from "@/components/cube";
import Header from "@/components/header";
import Space from "@/components/space";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";

import "./globals.css";

const inter = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Guan Ming Chiu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body
        className={cn(inter.className, "h-full text-black dark:text-white")}
      >
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <Header />
          <div className="absolute z-10 h-full w-full bg-white dark:bg-black">
            <Space>
              <Cube />
            </Space>
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
