import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import Space from "@/components/space";
import { cn } from "@/lib/utils";

import "./globals.css";

const inter = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Guan Ming Chiu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "h-full w-full")}>
        <div className="absolute z-10 h-full w-full">
          <Space></Space>
        </div>
        {children}
      </body>
    </html>
  );
}
